{% set name = "robustness" %}
{% set version = "1.2.1.post1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 18a0b2ed7345d85f3291d609dc5ad23946e9e71e6b1a8c003d0d51c8b1e98c32

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  # currently not available on osx or win

requirements:
  host:
    - python
    - pip
  run:
    - python
    - cox
    - dill
    - gitpython
    - gputil
    - grpcio
    - matplotlib-base
    - numpy
    - pandas
    - psutil
    - py3nvml
    - scikit-learn
    - scipy
    - seaborn
    - pytables
    - tensorboardx
    - pytorch
    - torchvision
    - tqdm

test:
  imports:
    - robustness
    - robustness.cifar_models
    - robustness.imagenet_models
    - robustness.tools

about:
  home: https://robustness.readthedocs.io/en/latest/index.html
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Tools for Robustness
  doc_url: https://robustness.readthedocs.io/en/latest/index.html
  dev_url: https://github.com/MadryLab/robustness

extra:
  recipe-maintainers:
    - oblute
    - rluria14
    - ndmaxar
